language: go
sudo: false

matrix:
  include:
    - go: 1.5
    - go: 1.6
    - go: 1.7
    - go: 1.8
    - go: 1.9
    - go: "1.10"

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/tools/cmd/goimports

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - diff -u <(echo -n) <(goimports -d .)
  - go tool vet .
  - go test -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
